name: auto-update

on:
  schedule:
    - cron: "0 8 * * *" # 17:00 JST = 野村證券の米国株の注文受付終了時間後
  push: {}

permissions:
  contents: write # to commit
  id-token: write # to use aws-actions/configure-aws-credentials

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pip install
        run: pip install --break-system-packages -r requirements.txt
      - name: Fetch Nomura's Foreign Stock List
        run: python fetch_nomura_foreign_stock_list.py
      - name: Configure AWS Credentials for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-region: ap-northeast-1
          # gh secret set AWS_ACCOUNT_ID --body "123456789012"
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/kabu-json-github-actions-role
          role-session-name: github-actions-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}
      - name: Upload to S3
        run: |
          aws s3 cp nomura_foreign_stock_list.json s3://kabu-json-public-static-data-bucket/kabu-json-nomura-foreign-stocks/v1/nomura_foreign_stock_list.json --content-type application/json
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add nomura_foreign_stock_list.json
          git commit -m "Update json files $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "No changes to commit"
